### ISSUE TITLE
`HOME_DIR` is not defined, leading to Error UnExpected

### ISSUE THREAD

**Issue by nopeless** [d-kimuson/ts-type-expand#326]
`src/utils/logger.ts`

`process.env["HOME"]` is not defined

I'm using Windows 11

**Comment by d-kimuson** [comment]
@nopeless Thanks for the report.
It looks like I need to modify the following.

https://github.com/d-kimuson/ts-type-expand/blob/master/packages/ts-type-expand-plugin/src/logger.ts#L14

```diff
-const HOME_DIR = process.env["HOME"]
+const HOME_DIR = process.env[process.platform == "win32" ? "USERPROFILE" : "HOME"]
```

I will release the fixed version after checking it on the windows machine at hand.
Please be patient.

**Comment by nopeless** [comment]
I have temporarily fixed this issue by defining HOME to be USER PROFILE in my windows machine. Take your time.

**Comment by d-kimuson** [comment]
@nopeless 
Thank you!
I made the change to refer to USERPROFILE on windows.
However, on my windows machine, the extension did not work properly with error #327.
I will close this issue as #327 will be addressed.

As a temporary workaround, I'll recommend using WSL if possible.
