### ISSUE TITLE
Stopped working completely

### ISSUE THREAD

**Issue by cesek-navisys** [d-kimuson/ts-type-expand#373]
It simply stopped working - no error and nothings shows up. Is there any problem with WSL2 (Windows Subsystem Linux)?

**Comment by zackhall** [comment]
I see the same issue on Mac.

**Comment by iloveitaly** [comment]
same issue here

**Comment by d-kimuson** [comment]
Thanks to you guys for your reports.
Close because it seems to be the same problem as #353 :pray:
