### ISSUE TITLE
Suggestion to modify default Compact Property Length in treeview

### ISSUE THREAD

**Issue by TonyGravagno** [d-kimuson/ts-type-expand#374]
Please note from the following that the width of the treeview seems to be limited compared to the width of the view window that contains it. In this example, the props type is TextFieldProps but it's shown as "props: Te...", and yet there is plenty of room for the full display.  
Thanks!
![image](https://github.com/d-kimuson/ts-type-expand/assets/499473/576122cd-afb0-4776-884e-2233c4f620e0)

**Comment by TonyGravagno** [comment]
Whoops! Just found it in settings. Never mind on the enhancement. However, a 10 character default seems very small. I expanded to 80 and when I resize the view window the tree automatically shows the elipsis at the right margin limit. Maybe a new default to 80 for people to downsize if desired?

![image](https://github.com/d-kimuson/ts-type-expand/assets/499473/15258a95-8574-4445-b4af-e01cab7117cd)
![image](https://github.com/d-kimuson/ts-type-expand/assets/499473/14aa9fcd-c801-40f2-bbb4-391f8f53f41c)

**Comment by d-kimuson** [comment]
Thanks for the idea! I was using it with Compact Property Length myself and didn't realize the default was too small.

I will change it to 80 characters as you suggested.

**Comment by d-kimuson** [comment]
This changes are released on v1.0.6
https://github.com/d-kimuson/ts-type-expand/releases/tag/v1.0.6
