### ISSUE TITLE
Mapped-Types resolve as unsupported instead of correct type

### ISSUE THREAD

**Issue by jerichaux** [d-kimuson/ts-type-expand#384]
Hello!

First off: fantastic extension! This adds some _sorely_ needed typing information not provided out of the box with VScode, to say the least!

One issue of note which I believe is not touched upon by the other issues (apologies if I'm incorrect) is that mapped-types resolve as "unsupported". For example:
```
type OneToThree = 1 | 2 | 3;
type MappedOneToThree = {
  [key in OneToThree]: string;
};
```

would have an expected expanded type of:
```
MappedOneToThree
  1: string
  2: string
  3: string
```

but instead yields:
```
MappedOneToThree
  1: unsupported
  2: unsupported
  3: unsupported
```

Again, though, thank-you so much for this wonderful extension!

**Comment by d-kimuson** [comment]
Close.
