### ISSUE TITLE
Popup asking to allow network access after installing the extension

### ISSUE THREAD

**Issue by Robouste** [d-kimuson/ts-type-expand#385]
I installed the extension, went into the solution explorer to try it, and got a popup from Windows asking me if I allow VSCode to access my network.

Why? This make it look like a malicious extension.

**Comment by d-kimuson** [comment]
@Robouste 
Thank you for your question. I understand the concern about this seeming like a malicious extension, but let me explain the reason behind this.

The short answer is that **extensions receive type information via HTTP communication** from the TypeScript language server.

Details:

This extension needs to retrieve type information for the selected nodes in your code, which requires accessing the TypeScript compiler API or the tsserver (TypeScript language service) in watch mode. However, the built-in tsserver in VSCode does not provide an interface for third-party extensions to access it directly.

A simple solution would be to start a separate watch process for the compiler API specifically for this extension. However, this approach has significant drawbacks:

- It would lead to duplicate type-checking, making the process very slow and resource-intensive.
- It cannot leverage the configuration settings from VSCode's tsserver, which can cause issues with TypeScript version mismatches or incompatibility with solution-style tsconfig files.

Previously, this simple approach was used, but the drawbacks were substantial. To address these issues, the extension now uses a different approach leveraging the Language Service Plugin (LSP) provided by VSCode.

[The Languase Service Plugin](https://github.com/microsoft/TypeScript/wiki/Writing-a-Language-Service-Plugin) allows extensions to execute custom code when the tsserver is initialized, providing access to the compiler API context. This extension utilizes the Language Service Plugin to start an HTTP server when tsserver initializes. This HTTP server serves as an endpoint to receive type information requests. The network access permission prompt you see is related to this HTTP server.

Here's the workflow:

1. When you select a node in your code, the extension sends the node's location to the HTTP server started alongside the tsserver.
2. The server responds with the corresponding type information for that node.

While the previous simple approach seemed more straightforward, the issues it caused were significant. To provide a better experience, the current implementation using the Languase Service Plugin and Http Server was adopted. For more details, you can refer to this article (in Japanese) that explains the rationale behind this approach: https://zenn.dev/kimuson/articles/vscode_language_service_plugin

**Comment by Robouste** [comment]
Thank you for your detailed answer, it makes sense :)
