### ISSUE TITLE
Return type of "async () => {}" is displayed as "void"

### ISSUE THREAD

**Issue by kasugaiasuka** [d-kimuson/ts-type-expand#77]
There seems to be something wrong with the handling of async function objects.

**Steps to Reproduce**
1. Write the following code.
2. Open the ts-type-expand panel.
3. Point `foo`.

```typescript
const foo = async () => { };
```

**Expected**
`ts-type-expand` displays the return type of `foo` as `Promise<void>`.

**Actual**
It displays this type as `void`.

**Additional info**
`const bar= async (): Promise<void> => { };` will be displayed as `any`.

**Comment by d-kimuson** [comment]
Thanks for the report !
I was able to reproduce it by trying it in my environment. I'll fix it.

**Comment by d-kimuson** [comment]
fixed in #99

**Comment by d-kimuson** [comment]
#99 merged.
